const {Router} = require('express')
const router = Router()
const auth = require('./middleware/auth')
router.use('/',require('./router/page'))
router.use('/user',require('./router/user'))
router.use('/checkout',require('./router/checkout'))
router.use('/feedback',require('./router/feedback'))
router.use('/atribut',auth,require('./router/atribut'))
router.use('/oneclick',auth,require('./router/oneclick'))
router.use('/product',auth,require('./router/product'))
router.use('/promo',auth,require('./router/promo'))
router.use('/blog',auth,require('./router/blog'))
router.use('/vakansi',auth,require('./router/vakansi'))
router.use('/category',auth,require('./router/category'))
router.use('/slider',auth,require('./router/slider'))
router.use('/api',require('./router/api'))
module.exports = router